branches:
  only:
    - master
language: node_js
node_js: '10'
cache: npm
before_install:
  - npm install -g npm@latest
install:
  - npm install
script:
  - npm run lint
  - npm run coverage
  - npm run build
  - if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then cat ./coverage/lcov.info | ./node_modules/.bin/coveralls; fi
notifications:
  email:
    on_success: never
    on_failure: always