'@handbook/code-block':
  version: 1.1.0
  tag: latest
'@handbook/markdown-source-import':
  version: 1.1.0
  tag: latest
  packageJson:
    bin:
      'markdown-source-import': ./bin/markdown-source-import.js
    keywords:
      - markdown
      - readme
      - remark
'@handbook/*':
  version: 1.1.0
  tag: latest